import { zipSync, strToU8 } from 'fflate';
import { telemetryCSV } from './sim.mjs';
let database;
function db(){if(database)return database;database=new Promise((resolve,reject)=>{const request=indexedDB.open('dronelab-v1',1);request.onupgradeneeded=()=>{for(const store of ['runs','designs','checkpoint'])request.result.createObjectStore(store,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return database;}
export async function put(store,value){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction(store,'readwrite');tx.objectStore(store).put(value);tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('Browser storage transaction aborted'));});}
export async function list(store){const d=await db();return new Promise((resolve,reject)=>{const request=d.transaction(store).objectStore(store).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
export async function clearCheckpoint(){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('checkpoint','readwrite');tx.objectStore('checkpoint').clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error);});}
export function download(name,content,type='application/json'){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);}
export function runBundle(run){const files={'metadata.json':strToU8(JSON.stringify({...run.metadata,outcome:run.outcome,intervals:run.intervals,gusts:run.gusts,findings:run.findings},null,2)),'telemetry.csv':strToU8(telemetryCSV(run.samples)),'events.json':strToU8(JSON.stringify(run.events,null,2)),'inputs.json':strToU8(JSON.stringify(run.inputs||[],null,2)),'captures.json':strToU8(JSON.stringify(run.captures?.map(({image:_image,...c})=>c)||[],null,2))};for(const c of run.captures||[])if(c.image){const raw=atob(c.image.split(',')[1]);files['inspection_images/'+c.id+'.png']=Uint8Array.from(raw,x=>x.charCodeAt(0));}return zipSync(files);}
export function exportRun(run){download('dronelab-'+run.metadata.missionId+'-'+run.metadata.id.slice(0,8)+'.zip',runBundle(run),'application/zip');}
